### ISSUE TITLE
pftool should write MD chunk-info from single-task

### ISSUE THREAD

**Issue by jti-lanl** [mar-file-system/marfs#21] opened 2015-11-12 19:35 UTC
Gary points out that if all the write-threads writing N:1 data are also updating the MD file with chunk-info, there will be a lot of lock-contention for small writes.

We should let the updates be done en masse from a single thread.  However, we still need this done per-file in fuse.  Sounds like more conditionalization of the behavior of marfs_release(), based on details in the FileHandle.  Fuse could continue doing this in marfs_write() or marfs_release(), whereas pftool could do it in MARFS_Path::post_process(), or something.

**Comment by brettkettering** [comment] 2015-12-11 16:26
This needs to be done for the Open Science MarFS version. I think this is already done, but if not it needs to be done.

**Comment by cadejager** [comment] 2015-12-11 16:39
This was fixed by adding pre and post process option to pftool's Path.h

**Comment by jti-lanl** [comment] 2015-12-11 16:51
Apologies.  Re-opening this.  What we fixed with the pre/post process was installing xattrs, etc.

I agree that post_process() seems like a natural place to add writing the N:1 chunk-info into the MD file, but it doesn't do that, yet..  We need to investigate whether post_process() only gets called from a place in pftool where the whole file has been finished, or is it per-chunk (which wouldn't help), or is it per a one of those block thingies that contain many path_items (which might help, especially if they could be relied on to all be part of the same N:1 move)., and, if the latter, are the path_items all contiguous chunks of info?

Might not be too hard to resolve these questions.  Then we'd know whether we can just extend post_process(), or need some other hacked Path method to be called from somewhere else in pftool.

**Comment by cadejager** [comment] 2015-12-21 15:46
I tested this on a 100GB file while watching post_process with a print statement. The marfs chunk size was 2GB. Post process was only called once after the transfer was complete.

**Comment by brettkettering** [comment] 2015-12-21 16:24
The end result that we need for Open Science is that a file is seen to be the correct size at the end of the file writing. This should work for PACKED, UNI, and MULTI files.

A later update can provide interim sizes as the file is being copied.

Chris D. to verify that you see the call one time for each file type (UNI and MULTI for now because PACKED is done by the script).

**Comment by cadejager** [comment] 2015-12-21 21:54
I can confirm that on UNI and MULTI files the post_process is called once per file.

**Comment by brettkettering** [comment] 2015-12-21 22:39
Then, I propose that you close the issue.

Thanks,
Brett

**Comment by brettkettering** [comment] 2015-12-21 22:40
Open another issue for later to provide the size while the file is being copied, not just when it's done.

**Closed** 2015-12-22 14:37 UTC
Labels: enhancement
