### ISSUE TITLE
Xattr Not Being Created

### ISSUE THREAD

**Issue by atorrez** [mar-file-system/marfs#11] opened 2015-09-21 13:17 UTC
I ran make_uni_mult from the script directory on Friday and noticed that my quota script was not finding the files that were created.  It turns out that the files existed in the gpfs space but the only xattr for the file was as below for all files:

# file: uni.195
user.marfs_restart=0sAQA=

In addition, when I deleted these files (from the fuse mount) I could not find them in trash.

Alfred

**Comment by jti-lanl** [comment] 2015-09-21 20:36
I've explored this a little with the current version of marfs from github (i.e. matching what Alfred was using).  I believe the problem is that I've recently made the object-stream thread return a value that captures curl-errors, instead of just returning 1 for errors.  When we abort a write stream, our implementation causes the curl PUT to return CURLE_ABORTED_BY_CALLBACK.   When you use marfs fuse to overwrite an existing file, the kernel calls fuse with commands to do open then ftruncate.  This is why we needed to be able abort a PUT.  However, the codebase on github has missed the fact that it must now trap CURLE_ABORTED_BY_CALLBACK, instead of 1, on return.

My code in progress does this correctly, so it will be fixed when I check that in.

WORKAROUND:  You can work around this problem by deleting all the files that will be created by make_uni_multi.  For example:

    rm -rf /marfs/atorrez/d?

**Closed** 2015-09-21 20:36 UTC
Labels: fixed in pending commit
