### ISSUE TITLE
strip out DAL/MDAL build-options

### ISSUE THREAD

**Issue by jti-lanl** [mar-file-system/marfs#201] opened 2017-09-27 17:29 UTC
Making the DAL/MDAL builds conditional was done early on, so that we could have something to fall back on, for comparison, and maybe to limit the link requirements.  The approach and implementation have been proven out by now.

The issue with removing these is that the non-DAL build uses the old S3/curl approach.  We have an OBJECT DAL that can do all that, so retaining that option should be pretty straight-forward, but we don't have a place to test anymore.  We'd need an S3 repo to test with.

**Comment by gransom** [comment] 2019-08-19 16:15
Duplicate of #198

**Closed by gransom** 2019-08-19 16:15 UTC
Labels: TBD
